FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Ne pas copier le reste des fichiers, ils seront montés en volume
# Cela permet d'avoir node_modules dans le conteneur, mais le code source sur la machine hôte

EXPOSE 3000

CMD ["npm", "run", "dev"]
