services:
  # Frontend en mode développement avec Node 20
  frontend:
    image: node:20-alpine
    container_name: rag-frontend
    working_dir: /app
    volumes:
      - ./rag-frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      # Utiliser les adresses internes Docker au lieu de localhost
      - VITE_NEXTCLOUD_URL=http://nextcloud
      - VITE_NEXTCLOUD_USERNAME=admin
      - VITE_NEXTCLOUD_PASSWORD=admin_password
      - VITE_SUPABASE_URL=http://localhost:9000
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTl9.Quy04IFG2K7mCjIW2EU4ixoivlpsVR2yFB2v6n5GPLs
      # Désactiver les dépendances natives de Rollup
      - ROLLUP_SKIP_NODEJS_NATIVE_WRAPPERS=true
      # Configuration pour Vite/Rollup
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "mkdir -p node_modules && 
             npm ci --prefer-offline --no-audit && 
             npm run dev -- --host 0.0.0.0"
    networks:
      - rag-network

  # Qdrant - Base de données vectorielle pour RAG
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # API HTTP
      - "6334:6334"  # API gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

  # RAG Backend API - FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # On expose seulement sur le réseau interne, Nginx fera le proxy
    ports:
      - "8000:8000"
    env_file: ./backend/backend/core/.env
    volumes:
      #- ./backend:/app  # Pour le développement, permet de modifier les fichiers en direct
      - ./backend/data:/app/data  # Persistence des données (registre JSON)
      - /tmp:/tmp  
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - rag-network

  # Nginx - Serveur web et proxy inverse
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/chardouin.fr/html:/var/www/chardouin.fr/html:ro
      - /var/www/hardouinosteopathe.fr/html:/var/www/hardouinosteopathe.fr/html:ro
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rag-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: localai
      POSTGRES_PASSWORD: localai_password
      POSTGRES_DB: localai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount the initialization script
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  frontend_node_modules:
  qdrant_data:  # Stockage persistant pour Qdrant
  postgres_data:
    driver: local