version: '3.8'

services:
  rag-frontend:
    build:
      context: ./rag-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./rag-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - VITE_API_URL=http://localhost:8000/api
      - VITE_NEXTCLOUD_URL=https://chardouin.fr/nextcloud
    command: npm run dev
    networks:
      - app-network

  rag-backend:
    build:
      context: ./rag-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./rag-backend:/app
    ports:
      - "8000:8000"
    environment:
      - NEXTCLOUD_URL=http://nextcloud:80
      - NEXTCLOUD_USERNAME=admin
      - NEXTCLOUD_PASSWORD=admin_password
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network
    depends_on:
      - nextcloud

  nextcloud:
    image: nextcloud:latest
    ports:
      - "8080:80"
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=nextcloud-db
    volumes:
      - nextcloud-data:/var/www/html
    networks:
      - app-network
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html/chardouin.fr
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - rag-backend
      - nextcloud
    networks:
      - app-network

networks:
  app-network:

volumes:
  nextcloud-data:
  nextcloud-db:
