services:
  # Frontend en mode développement avec Node 20
  frontend:
    image: node:20-alpine
    container_name: rag-frontend
    working_dir: /app
    volumes:
      - ./rag-frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      # Utiliser les adresses internes Docker au lieu de localhost
      - VITE_NEXTCLOUD_URL=http://nextcloud
      - VITE_NEXTCLOUD_USERNAME=admin
      - VITE_NEXTCLOUD_PASSWORD=admin_password
      - VITE_SUPABASE_URL=http://localhost:9000
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTl9.Quy04IFG2K7mCjIW2EU4ixoivlpsVR2yFB2v6n5GPLs
      # Désactiver les dépendances natives de Rollup
      - ROLLUP_SKIP_NODEJS_NATIVE_WRAPPERS=true
      # Configuration pour Vite/Rollup
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "mkdir -p node_modules && 
             npm ci --prefer-offline --no-audit && 
             npm run dev -- --host 0.0.0.0"
    networks:
      - rag-network
    depends_on:
      - nextcloud

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud localhost 127.0.0.1
    networks:
      - rag-network
    depends_on:
      - nextcloud-db

  # Base de données Nextcloud
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - rag-network

  # Qdrant - Base de données vectorielle pour RAG
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # API HTTP
      - "6334:6334"  # API gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

  # RAG Backend API - FastAPI
  rag-backend:
    build:
      context: ./rag-backend
      dockerfile: Dockerfile
    container_name: rag-backend
    # On expose seulement sur le réseau interne, Nginx fera le proxy
    ports:
      - "8000:8000"
    env_file: ./rag-backend/.env
    volumes:
      - ./rag-backend:/app  # Pour le développement, permet de modifier les fichiers en direct
      - ./rag-backend/data:/app/data  # Persistence des données (registre JSON)
      - /tmp:/tmp  
    depends_on:
      - qdrant
      - nextcloud
    restart: unless-stopped
    networks:
      - rag-network

  # Nginx - Serveur web et proxy inverse
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d  # Configurations Nginx
      - ./nginx/ssl:/etc/nginx/ssl      # Certificats SSL gérés par Certbot
      - ./certbot/www:/var/www/certbot   # Challenge pour Certbot
      - ./nginx/logs:/var/log/nginx      # Logs
      - /var/www/chardouin.fr/html:/usr/share/nginx/html/chardouin.fr  # Site statique
    depends_on:
      - rag-backend
      - nextcloud
    restart: unless-stopped
    networks:
      - rag-network
      
  # Note: Le service Certbot a été supprimé car il n'est pas nécessaire
  # en environnement de développement. Pour la production, vous pouvez :
  # 1. Installer Certbot directement sur l'hôte
  # 2. Utiliser un service géré comme Cloudflare
  # 3. Configurer Let's Encrypt via votre hébergeur

networks:
  rag-network:
    driver: bridge

volumes:
  nextcloud_data:
  nextcloud_db:
  frontend_node_modules:
  qdrant_data:  # Stockage persistant pour Qdrant
