version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_URL=http://localhost:8081
      - KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true
      - KC_HTTP_RELATIVE_PATH=/
      # Configuration CORS
      - KC_SPI_CONNECTIONS_HTTP_DEFAULT_CLIENT_POLICY_PROVIDER=anonymous
      - KC_SPI_CONNECTIONS_HTTP_DEFAULT_CLIENT_POLICY_PROFILES=cors
      - KC_CORS=true
      - KC_CORS_ALLOWED_ORIGINS=http://localhost:5173 http://localhost:3000
      - KC_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - KC_CORS_EXPOSED_HEADERS=Content-Disposition,WWW-Authenticate
      - KC_CORS_ALLOW_CREDENTIALS=true
      # Configuration CSP - relaxée pour le développement
      # Désactiver complètement CSP pour le développement
      - KC_SPI_CONTENT_SECURITY_POLICY_PROVIDER=none
      # Ajout de headers personnalisés - accès total pour le développement
      - KC_HTTP_HEADER_CONTENT_SECURITY_POLICY=frame-ancestors 'self' http://localhost:* http://127.0.0.1:*
      - KC_HTTP_HEADER_X_FRAME_OPTIONS=ALLOW-FROM *
    command: start-dev
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  smtp:
    image: namshi/smtp
    environment:
      - RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16
      - MAILNAME=mail.newsflix.fr
      - SMTP_USER=noreply@newsflix.fr
      - SMTP_PASSWORD=enzo789luigi
    ports:
      - "25:25"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
