# ===============================
# RAG Backend Complete Configuration
# ===============================

metadata:
  project: rag-backend
  version: 1.0.0
  maintainer: edoardo@example.com

retrieval:
  top_k: 500                       # Number of documents to retrieve per query
  hybrid: true                    # Use hybrid (dense + sparse) retrieval
  split_prompt: true              # Whether to split prompt into subquestions
  rerank: false                    # Whether to rerank retrieved documents
  use_hyde: false                 # Whether to use HyDE hypothetical answer
  embedder: openai                # Use OpenAI embeddings (options: openai, huggingface)
  vectorstore:
    path: ./data/vectorstore      # Path to vector store
    type: qdrant                  # qdrant, faiss, chroma, etc.
    host: qdrant
    port: 6333
    collection: rag_documents1536
  filter_fallback: false           # Fallback to no-filter if filtered results are empty
  supported_types: ["email", "pdf", "contract"]
  min_score: 0.2                  # Minimum score threshold for retrieved docs

embedder:
  provider: openai                # openai, huggingface
  model: text-embedding-3-small

llm:
  provider: openai                # openai, azure, local, etc.
  model: gpt-4.1-nano
  temperature: 0.7
  max_tokens: 512
  api_base: https://api.openai.com/v1
  timeout: 30                     # seconds
  available_models: ["gpt-4.1", "gpt-4.1-nano", "gpt-4.1-mini"]
  system_prompt: |
    Tu es un assistant qui répond à la question en t'appuyant uniquement sur les passages ci-dessous. Pour chaque passage utilisé, indique le numéro de la source entre crochets [Source X]. Si aucune information pertinente n'est trouvée dans les passages, indique-le.\n

api:
  host: 0.0.0.0
  port: 8000
  cors:
    enabled: true
    allowed_origins: ["*"]        # Use ["*"] for development only!
  auth:
    enabled: false                # Set to true to require API key
    api_key_env: RAG_API_KEY      # Name of env var for API key

logging:
  level: INFO                     # DEBUG, INFO, WARNING, ERROR
  file: ./logs/rag-backend.log

monitoring:
  enabled: true
  prometheus_endpoint: /metrics

ingestion:
  supported_types: [
    ".pdf",    # Fichiers PDF
    ".docx",   # Documents Microsoft Word
    ".txt",    # Fichiers texte brut
    ".md",     # Fichiers Markdown
    ".ppt",    # Présentations PowerPoint (ancien format)
    ".pptx",   # Présentations PowerPoint
    ".csv",    # Fichiers de données CSV
    ".json",   # Fichiers JSON
    ".eml",  # Emails
    #"odt",    # Documents OpenDocument Text
    #"ods",    # Feuilles de calcul OpenDocument
    ".xls",    # Feuilles de calcul Excel (ancien format)
    ".xlsx",   # Feuilles de calcul Excel (format Office 2007+)
    ".xlsm",   # Feuilles de calcul Excel avec macros
    ".fods",   # Format OpenDocument Flat XML pour les feuilles de calcul
    ".gdoc",   # Google Documents
    ".gsheet", # Google Sheets
    ".gslides" # Google Slides
  ]
  batch_size: 10
  schedule_cron: "0 * * * *"      # Every hour

features:
  enable_hybrid: true
  enable_filter_extraction: true
  enable_source_attribution: true
  enable_fallback: true

security:
  secrets_via_env: true           # Store all secrets in env variables
  allowed_hosts: ["localhost", "127.0.0.1"]

# ===============================
# Place secrets in environment variables, not here!
# Example: export OPENAI_API_KEY=your-key
# ===============================
sync:
  # Configuration de la synchronisation Gmail
  gmail:
    enabled: true
    # Requête de filtrage (utiliser la syntaxe de recherche Gmail)
    query: "is:unread"
    # Dossiers à synchroniser
    folders: 
      - "INBOX"
      - "SENT"
    # Nombre maximum d'emails à récupérer par dossier
    limit_per_folder: 500
    # Ne pas récupérer les pièces jointes
    no_attachments: false
    # Forcer la réingestion des emails déjà traités
    force_reingest: false

  # Configuration de la synchronisation Outlook
  outlook:
    enabled: true
    # Requête de filtrage (utiliser la syntaxe de recherche Microsoft Graph)
    query: "isRead eq false"
    # Dossiers à synchroniser (noms standardisés Outlook)
    folders:
      - "inbox"
      - "sentitems"
    # Nombre maximum d'emails à récupérer par dossier
    limit_per_folder: 500
    # Ne pas récupérer les pièces jointes
    no_attachments: false
    # Forcer la réingestion des emails déjà traités
    force_reingest: false

  # Configuration du traitement des emails après synchronisation
  email_processing:
    enabled: true
    # Nombre maximum d'emails à traiter après chaque synchronisation
    limit_per_sync: 500
    # Activer les actions automatiques basées sur la classification
    auto_actions: false
    # Types d'actions automatiques à effectuer (reply, forward, flag_important, etc.)
    allowed_actions:
      - "flag_important"
      - "archive"
    # Priorité minimale pour les actions automatiques (low, medium, high)
    min_priority: "medium"

# Configuration des journaux
logging:
  # Niveau de journalisation (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Fichier de journalisation
  file: "logs/sync_service.log"
  # Taille maximale du fichier de journalisation en Mo
  max_size_mb: 10
  # Nombre de fichiers de sauvegarde à conserver
  backup_count: 5

# Configuration des chemins
paths:
  # Répertoire des jetons (relatif à la racine du projet)
  tokens: "auth/tokens"